# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f8569dbb90dd85f19cf02f85f8d77ba5988f1f73180ff990d1346f5d495622bb4e338f5489131454cf8dae7fe4bf0c68bd82dc833ca0acabb8090eeb61fdf38

test:
  secret_key_base: 9b423b3b429c4f068a2c082613d2d656a4aa7fd514e21299fa563f4f6d8d5817c8e010a77644bb4639ffc6fb549889d8f86bc060c0fca8a3d28c6b51126a57c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
